<?xml version="1.0" encoding="UTF-8"?>

<!--
Nombre: [David Ucendo Plaza]
Curso: [ASIR1]
Fecha: [3/04/2025]
Ejercicio: [Ejercicio_2-3]
-->

<!DOCTYPE aeropuertos [
   <!ELEMENT aeropuertos (aeropuerto+)>
   <!ELEMENT aeropuerto (nombre, cerrado?)>
   <!ELEMENT nombre (#PCDATA)>
   <!ELEMENT cerrado (#PCDATA)>
]>
<aeropuertos>
   <aeropuerto>
      <nombre>Berlin Sch√∂nefeld (SFX)</nombre>
   </aeropuerto>
   <aeropuerto>
      <nombre>Berlin Tempelhof (THF)</nombre>
      <cerrado>2008</cerrado>
   </aeropuerto>
</aeropuertos>
