<?xml version="1.0" encoding="UTF-8"?>

<!--
Nombre: [David Ucendo Plaza]
Curso: [ASIR1]
Fecha: [3/04/2025]
Ejercicio: [Ejercicio_2-8]
-->

<!DOCTYPE contabilidad [
<!ELEMENT contabilidad (apunte+)>
<!ELEMENT apunte (fecha, cantidad, concepto)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT concepto (#PCDATA)>
<!ELEMENT ingreso EMPTY>
<!ELEMENT gasto EMPTY>
]>

<contabilidad>
    <apunte>
        <ingreso />
        <fecha>24 de febrero de 2011</fecha>
        <cantidad>100.00 €</cantidad>
        <concepto>Salario</concepto>
    </apunte>
    <apunte>
        <gasto />
        <fecha>28 de febrero de 2011</fecha>
        <cantidad>74.15 €</cantidad>
        <concepto>Recibo luz</concepto>
    </apunte>
</contabilidad>
