<?xml version="1.0" encoding="UTF-8"?>

<!--
Nombre: [David Ucendo Plaza]
Curso: [ASIR1]
Fecha: [3/04/2025]
Ejercicio: [Ejercicio_2-4]
-->

<!DOCTYPE vuelos [
   <!ELEMENT vuelos (vuelo+)>
   <!ELEMENT vuelo (origen | destino)*>
   <!ELEMENT origen (#PCDATA)>
   <!ELEMENT destino (#PCDATA)>
]>
<vuelos>
   <vuelo>
      <origen>Valencia (VLC)</origen>
      <destino>Londres Heathrow (LHR)</destino>
   </vuelo>
   <vuelo>
      <origen>Berlin Sch√∂nefeld (SFX)</origen>
      <destino>Paris Charles de Gaulle (CDG)</destino>
   </vuelo>
</vuelos>
