=== DavidUcPl/VisualSC/05.02. Validación XML - DTD II Requisitos de finalización/EJERCICIO_03/index.dtd
<!ELEMENT panel (nombre_aeropuerto, vuelo+)>
<!ATTLIST panel fecha CDATA #REQUIRED>

<!ELEMENT nombre_aeropuerto (#PCDATA)>

<!ELEMENT vuelo (diario?, origen, destino, hora_salida, hora_llegada)>
<!ATTLIST vuelo codigo ID #REQUIRED>
<!ATTLIST vuelo estado (C | E | R) \"E\">

<!ELEMENT diario (#PCDATA)>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT destino (#PCDATA)>
<!ELEMENT hora_salida (#PCDATA)>
<!ELEMENT hora_llegada (#PCDATA)>

=== DavidUcPl/VisualSC/05.02. Validación XML - DTD II Requisitos de finalización/EJERCICIO_03/index.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
Nombre: [David Ucendo Plaza]
Curso: [ASIR1]
Fecha: [2/04/2025]
Ejercicio: [Ejercicio_03]
-->

<!DOCTYPE panel SYSTEM "index.dtd">

<panel fecha="20/12/2013">
    <nombre_aeropuerto>JFK</nombre_aeropuerto>
    <vuelo codigo="V22" estado="R">
        <diario>SI</diario>
        <origen>New York</origen>
        <destino>Chicago</destino>
        <hora_salida>9:30</hora_salida>
        <hora_llegada>11:30</hora_llegada>
    </vuelo>
    <vuelo codigo="V23" estado="C">
        <diario>NO</diario>
        <origen>New York</origen>
        <destino>Miami</destino>
        <hora_salida>10:15</hora_salida>
        <hora_llegada>11:15</hora_llegada>
    </vuelo>
</panel>
